apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
  app: nginx
    tier: web
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
      template:
    metadata:
      labels:
      app: nginx
      spec:
        containers:
          - name: web
            image: nginx:latest 